name: Deploy

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          source: "./"
          target: /home/maciek/apps/dixit
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            set NVM_DIR=/home/maciek/.nvm
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            set PATH=${PATH}:/home/maciek/.local/share/pnpm
            nvm use
            pnpm --version
            node --version
            cd /home/maciek/apps/dixit
            # Launch server
            cd server
            pnpm install
            pm2 start --name "server" pnpm -- start
            # Launch Vite app
            cd ../app
            pnpm install
            pm2 start --name "frontend" pnpm -- run dev
