name: Deploy

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: copy files with rsync over SSH
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/maciek/apps/dixit
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_port: ${{ vars.SSH_PORT }}
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            echo "Set up paths..."
            export NVM_DIR=/home/maciek/.nvm
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            export PATH=${PATH}:/home/maciek/.local/share/pnpm
            source /home/maciek/.bashrc
            echo $PATH
            nvm install 21
            nvm use 21
            echo $(pnpm --version)
            echo $(node --version)
            # Install dependencies
            echo "Install dependencies..."
            pnpm install -g pm2
            # Navigate to project directory
            cd /home/maciek/apps/dixit
            nvm use
            # Launch server
            echo "Launch Server..."
            cd server
            pnpm install
            pm2 start --name "server" pnpm -- start
            # Launch Vite app
            echo "Launch App..."
            cd ../app
            pnpm install
            pm2 start --name "frontend" pnpm -- run dev
