name: Deploy

on: [push]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          source: "./"
          target: /home/maciek/apps/dixit
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            source /home/maciek/.bashrc
            cd /home/maciek/apps/dixit
            # Launch server
            cd server
            npm install
            pm2 start --name "server" npm -- start
            # Launch Vite app
            cd ../app
            npm install
            pm2 start --name "frontend" npm -- run dev
